version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 18.x
    commands:
      - npm install -g aws-cdk
      - npm install
  build:
    commands:
      - cdk synth
artifacts:
  files:
    - "**/*"
