version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 18.16.1
    commands:
      - npm install -g aws-cdk
      - npm install
  build:
    commands:
      - cdk synth
      - cdk deploy --require-approval never
artifacts:
  files:
    - "**/*"
